[project]
name = "reg-batch-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi==0.128.0",
    "psycopg2==2.9.11",
    "pytest==9.0.2",
    "python-dotenv==1.2.1",
    "python-multipart==0.0.22",
]
[tool.pytest.ini_options]
pythonpath = ["."]
